import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './component/navbar'
import Footer from './component/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MYID - Unique ID in Web3',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar />
        <main classNameNameName={inter.classNameNameName}>
          {children}
        </main>
        <Footer />
      </body>

    </html>
  )
}
